feat: twir addon
FrankerFaceZ/Add-Ons pull request #207
Opened 2024-03-16 20:00 UTC by crashmax-dev

This add-on for https://twir.app adds a command suggestion.
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/15673111/9c309319-fc23-4971-90a0-7b7cb4531be3)

2024-03-16 20:39 UTC, SirStendec requested changes
Hey there! Thanks for submitting a new add-on.

The big thing here is that you need to set `enabled` to `true` in your manifest for the add-on to get built. Everything else is technically fine, but I suggest you change how you're handling when rooms are added/removed as discussed in my comments.

As an aside, I think this is super neat. I've always intended to eventually have a bot command tab-completion thing in FrankerFaceZ but I've never actually gotten around to it. I might have to see if I can mess with the command autocomplete provider to let us just specify a command uses something other than `/` in order to remove the need for a pre-send event here.

2024-03-16 20:39 UTC, SirStendec commented on src/twir/index.js
> +		this.tabCommands = [];
So, when a `chat:room-remove` event is being fired, you're just clearing your list of commands. This is, in theory, fine.

The problem is that when a user navigates to a new channel, `chat:room-add` is called immediately for the new room. `chat:room-remove` is called after a short delay. (There's a reference counting system in place for room data and removals happen after a short delay to protect against any quick leave-join-leave-join nonsense.)

In practice, this means that your tabCommands array is likely to be cleared when a user navigates between channels unless your API is particularly slow. Maybe store the commands in a map by room ID, and flatten it into an array as necessary? This makes me notice that the get-tab-commands event doesn't include the current channel, so I'll try to add something for that next time I'm paying attention.

2024-03-16 20:39 UTC, SirStendec commented on src/twir/index.js
> +		if (message.startsWith('/') && message.includes(ZWE_SYMBOL)) {
I'd prefer if you were more specific with the test for `ZWE_SYMBOL` here. It should always be at the start such that a command is `/${ZWE_SYMBOL}something` so you could have a regular expression like
```javascript
// top of file
const COMMAND_MATCHER = new RegExp(`^/${ZWE_SYMBOL}(.+)`);

// later
const match = COMMAND_MATCHER.exec(message);
if ( match )
    event.message = `!${match[1]}`;
```

This protects against the case where a user happens to have your special character in their command for whatever reason, which could in theory happen with some commands (an example being a custom ban/timeout reason). Users can be weird so I try to anticipate stuff like that.

2024-03-16 20:39 UTC, SirStendec commented on src/twir/manifest.json
> +  "enabled": false,
You should set `enabled` to `true` when submitting a new add-on, for it to be built. If you don't want the add-on to be included in the add-on's list you can set `unlisted` to `true` as well.

2024-03-17 00:40 UTC, SirStendec commented
Update: I added support for ! commands in 8807e09ea324db3def925a1e79aa05865879dd6b

This should simplify your logic a lot, since you can just specify that your commands have `prefix: '!'` and they'll be displayed/inserted/completed that way.

Example:
```javascript
ffz.on('chat:get-tab-commands', e => e.commands.push({
    prefix: '!',
    name: '8ball',
    description: 'oooooo spoookey',
    permissionLevel: 0,
    ffz_group: 'Quoteconut (Bot)',
    commandArgs: [
        {name: 'question', isRequired: true}
    ]
}));
```
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/14036657/c02cd809-a383-4a27-ab09-6363fcbf5c13)

2024-03-17 08:22 UTC, crashmax-dev commented on src/twir/index.js
> +		if (message.startsWith('/') && message.includes(ZWE_SYMBOL)) {
`ZWE_SYMBOL` outdated

2024-03-17 17:49 UTC, merged