feat(screenshotter): add setting to save as file & copy
FrankerFaceZ/Add-Ons pull request #227
Opened 2024-07-27 23:32 UTC by ConnorDoesDev

2024-07-30 21:18 UTC, SirStendec requested changes
I'm not satisfied with how you've implemented the settings here.

2024-07-30 21:18 UTC, SirStendec commented on src/screenshoter/index.js
>  			const clipboard = this.settings.get(`${this.settingsNamespace}.clipboard`)
You should probably switch this to an `else if ( clipboard ) { ... } else { ... }` so that multiple things aren't happening unexpectedly when you save.

Actually, you might consider either two separate settings (one for saving to file, one for copying to clipboard) and just do them separately. Or combine your settings into a single setting using a combo box to choose the desired behavior.

2024-07-30 21:40 UTC, ConnorDoesDev reviewed
Went with your suggestion of having seperate settings, thanks!

2024-07-31 01:10 UTC, SirStendec requested changes

2024-07-31 01:10 UTC, SirStendec commented on src/screenshoter/index.js
> +			if (!this.settings.get(`$this.settingsNamespace}.download`) || !this.settings.get(`$this.settingsNamespace}.copy`)) return this.saveToClipboard(blob); // Default to clipboard if both settings r tu
This line has a typo. Missing a `{`, which means the first setting will never have a value because it's a non-existent key.

2024-08-01 14:24 UTC, ConnorDoesDev commented on src/screenshoter/index.js
> +			if (!this.settings.get(`$this.settingsNamespace}.download`) || !this.settings.get(`$this.settingsNamespace}.copy`)) return this.saveToClipboard(blob); // Default to clipboard if both settings r tu
fixed it, mb

2024-08-03 11:57 UTC, ConnorDoesDev commented
Little friday bump ^

2024-08-06 21:15 UTC, SirStendec commented
Apologies, I didn't want to accept this until I fixed the issues with the CI system.

That said, I noticed that you haven't updated the manifest to bump the add-on's version number. Please do so.

2024-08-12 17:28 UTC, merged