New Account Highlighter 1.0.0
FrankerFaceZ/Add-Ons pull request #39
Opened 2021-02-06 10:42 UTC by 1F916

This addon highlights new Twitch accounts that are newer than a specified age.

2021-02-06 23:38 UTC, SirStendec requested changes
Couple minor things.

The main thing to fix is the potential exception in the chat tokenizer.

2021-02-06 23:38 UTC, SirStendec commented on src/new-account-highlighter/index.js
> +				let minuid = NewAccountHighlighter.Mappings[minage].uid;
Potential TypeError if Mappings has no value for `minage`.

You are adding your tokenizer in your constructor, so it can be called by the chat stack before your add-on loads / enables which would leave the mapping object empty.

2021-02-06 23:38 UTC, SirStendec commented on src/new-account-highlighter/index.js
> +			ui: {
You should probably add a default color here, since you're effectively setting a default value when you use this, to show users what it is.

2021-02-07 08:14 UTC, 1F916 commented
Thank you for reviewing my pull request.
I submitted a new commit that should address your concerns, plus some minor polishing.

2021-02-07 08:22 UTC, merged