Add First Message Highlighter 1.0.0
FrankerFaceZ/Add-Ons pull request #93
Opened 2021-12-01 14:53 UTC by Gadsee

Hello,

This add-on provides community-driven chats a way of identifying newcomers. Twitch already added a highlight for overall first-time chatters. However, this add-on expands that functionality by highlighting all users sending a message for the first time in the current session.

I've tried adhering to this repositories code-style as much as I could. I took inspiration from New Account Highlighter and Chat Repetition Detector. If any of either authors feel like I've copied their code, I'm happy to think of alternatives.

Please comment on any improvement opportunities or changes needed.

2021-12-01 18:18 UTC, SirStendec requested changes

2021-12-01 18:18 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +	known_users = [];
You want to be, at a minimum, using a Set rather than an array. Sets are significantly faster for membership checking over large arrays and, particularly, when the element you're looking for isn't at the start: https://jsbench.me/odkwnuizce/1

2021-12-01 18:18 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +		this.known_users = [];
onUnload() is unnecessary for this use case. onDisable() always runs before onUnload()

2021-12-01 18:18 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +	onLoad() {
Please avoid including stub onLoad() and onUnload() methods as doing so creates pointless work when enabling a module.

2021-12-01 18:59 UTC, Gadsee commented on src/first-message-highlighter/index.js
> +				if (outerThis.known_users.includes(msg.user.userID)) return tokens;
I am unsure how exactly "caching the state onto the msg object" is supposed to be done, is there an example somewhere? Excuse my poor JS skills, I come from Java/C#.

2021-12-01 18:59 UTC, Gadsee commented on src/first-message-highlighter/index.js
> +		this.chat.addTokenizer(MessageHighlighter);
How do I remove the tokenizer? I did not find any method for that in the chat index.js of the FFZ repo

2021-12-01 21:55 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +				if (outerThis.known_users.includes(msg.user.userID)) return tokens;
Just be like
```javascript
if ( msg.fh_known == null )
    msg.fh_known = outerThis.known_users.has(msg.user.userID);
```

2021-12-01 21:57 UTC, Gadsee commented on src/first-message-highlighter/index.js
> +		this.chat.addTokenizer(MessageHighlighter);
Saw the API change, thanks for that! :)

2021-12-01 21:57 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +		this.chat.addTokenizer(MessageHighlighter);
Yeah, good point. As of the latest FFZ I just added a method to remove tokenizers.

Make sure you emit a `chat:update-lines` event after adding / removing your tokenizer. Just need a
```javascript
this.chat.addTokenizer(...);
this.emit('chat:update-lines');
```

Note: You don't *have* to do it after adding the tokenizer, but you absolutely need to after removing one.

2021-12-01 21:59 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +					'first-message'
I missed this the first time, but as you're using a new highlight reason, please register a human readable string for your highlight reason:
```javascript
this.chat.addHighlightReason('first-message', "User's First Message This Session");
```
or the like

2021-12-01 22:08 UTC, Gadsee commented
Implemented all the recommended changes, thank you so much for your outstanding help! Requested a re-confirm after writing this message 🙂

2021-12-06 17:14 UTC, SirStendec requested changes

2021-12-06 17:14 UTC, SirStendec commented on src/first-message-highlighter/index.js
> +		this.known_users.add(ffz.site.getUser().id);
This will break if there isn't a logged in user. Admittedly that's not particularly likely, but the result of `getUser()` should be checked to ensure it's not a null value.

2022-01-02 13:19 UTC, Gadsee commented
Friendly bump? Didn't want to annoy over the Christmas and year-change-days.

2022-02-11 19:36 UTC, merged